import { Urbanist } from "next/font/google";


const urbanist = Urbanist({
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Profast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#EAECED]">
      <body className={`${urbanist.variable} `}>
        
        {children}
  
      </body>
    </html>
  );
}
