import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Profast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#EAECED]">
      <body className={`${urbanist.variable} w-11/12 mx-auto`}>
        <header className="mt-8">
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
