import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAuthProvider";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Profast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#EAECED]">
      <body className={`${urbanist.variable} w-11/12 mx-auto`}>
        <NextAuthProvider>
       
          <Toaster position="	top-right" />
          <header className="mt-8">
            <Navbar />
          </header>
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
